Create publish stack API
codio/codio-api-js pull request #12
Opened 2021-11-25 12:09 UTC by AndreyNikitin

https://codio.myjetbrains.com/youtrack/issue/codio-12280

2022-01-05 11:00 UTC, ksimuk requested changes

2022-01-05 11:00 UTC, ksimuk commented
need readme update with examples

2022-01-10 09:35 UTC, AndreyNikitin commented
get client/secret from env

2022-01-12 09:44 UTC, ksimuk approved these changes

2022-01-13 11:14 UTC, sergei-bronnikov approved these changes

2022-01-13 11:15 UTC, merged